# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hotelReservationForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(583, 588)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 10, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.calendarWidget = QtWidgets.QCalendarWidget(Dialog)
        self.calendarWidget.setGeometry(QtCore.QRect(160, 40, 280, 155))
        self.calendarWidget.setObjectName("calendarWidget")
        self.labelDateOfReservation = QtWidgets.QLabel(Dialog)
        self.labelDateOfReservation.setGeometry(QtCore.QRect(40, 50, 101, 16))
        self.labelDateOfReservation.setObjectName("labelDateOfReservation")
        self.labelNoOfDays = QtWidgets.QLabel(Dialog)
        self.labelNoOfDays.setGeometry(QtCore.QRect(50, 220, 81, 16))
        self.labelNoOfDays.setObjectName("labelNoOfDays")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(170, 220, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.labelRoomType = QtWidgets.QLabel(Dialog)
        self.labelRoomType.setGeometry(QtCore.QRect(50, 270, 61, 16))
        self.labelRoomType.setObjectName("labelRoomType")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(170, 270, 351, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButtonCalculateRoomRent = QtWidgets.QPushButton(Dialog)
        self.pushButtonCalculateRoomRent.setGeometry(QtCore.QRect(230, 460, 131, 23))
        self.pushButtonCalculateRoomRent.setObjectName("pushButtonCalculateRoomRent")
        self.dateOfReservationInfo = QtWidgets.QLabel(Dialog)
        self.dateOfReservationInfo.setGeometry(QtCore.QRect(40, 310, 481, 21))
        self.dateOfReservationInfo.setText("")
        self.dateOfReservationInfo.setObjectName("dateOfReservationInfo")
        self.roomRentInfo = QtWidgets.QLabel(Dialog)
        self.roomRentInfo.setGeometry(QtCore.QRect(30, 490, 531, 41))
        self.roomRentInfo.setText("")
        self.roomRentInfo.setObjectName("roomRentInfo")
        self.noOfDaysInfo = QtWidgets.QLabel(Dialog)
        self.noOfDaysInfo.setGeometry(QtCore.QRect(40, 350, 481, 21))
        self.noOfDaysInfo.setText("")
        self.noOfDaysInfo.setObjectName("noOfDaysInfo")
        self.roomTypeInfo = QtWidgets.QLabel(Dialog)
        self.roomTypeInfo.setGeometry(QtCore.QRect(40, 400, 481, 21))
        self.roomTypeInfo.setText("")
        self.roomTypeInfo.setObjectName("roomTypeInfo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Hotel Room Reservation"))
        self.labelDateOfReservation.setText(_translate("Dialog", "Date of Reservation"))
        self.labelNoOfDays.setText(_translate("Dialog", "Number of Days"))
        self.labelRoomType.setText(_translate("Dialog", "Room Type"))
        self.comboBox.setItemText(0, _translate("Dialog", "Single Room"))
        self.comboBox.setItemText(1, _translate("Dialog", "Family Room"))
        self.comboBox.setItemText(2, _translate("Dialog", "Double Room"))
        self.pushButtonCalculateRoomRent.setText(_translate("Dialog", "Calculate Room Rent"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
